/*Query each category*/
SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 1;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 2;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 3;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 4;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 5;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 6;

