/*QUERIES FOR EACH TABLE*/ 
SELECT * FROM SUBCATEGORY;
SELECT * FROM CATEGORY;
SELECT * FROM TIPS;
SELECT * FROM SEASON;
SELECT * FROM TIP_SEASON;

/*QUERIES FOR EACH CATEGORY*/ 

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 1;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 2;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 3;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 4;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 5;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, C_NAME FROM TIPS t
JOIN CATEGORY c 
ON t.C_ID = c.C_ID
WHERE t.C_ID = 6;

/*QUERIES FOR EACH SUBCATEGORY 
CHANGE WHERE t.SUB_ID = 1; to any number between 1-14 for the SUBCATEGORY you are looking for.*/

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 1;


/*Sample query for tips that have a Category for 'Appliances' and a Subcategory for 'Dishwasher'*/

SELECT T_DESC_ENGLISH, C_NAME, SUB_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN CATEGORY c ON
c.C_ID = t.C_ID 
JOIN SUBCATEGORY sc ON
sc.SUB_ID = t.SUB_ID
WHERE c.C_ID = 1 AND sc.SUB_ID = 4;


/*Sample query for tips that are in the category ID 'around town' and have the subcategory ID 'electric vehicles'*/

SELECT T_DESC_ENGLISH, S_NAME, C_NAME, SUB_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID
JOIN CATEGORY c ON 
c.C_ID = t.C_ID
JOIN SUBCATEGORY sc ON
sc.SUB_ID = t.SUB_ID
WHERE c.C_ID = 2 AND sc.SUB_ID = 6;




