SELECT T_DESC_ENGLISH,T_DESC_SPANISH,C_NAME, SUB_NAME, S_NAME FROM TIPS t
JOIN CATEGORY c ON 
t.C_ID = c.C_ID
JOIN SUBCATEGORY s ON 
t.SUB_ID = s.SUB_ID
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON sn ON
sn.S_ID = ts.S_ID 
WHERE t.C_ID = 1 AND t.SUB_ID = 2 AND sn.S_ID = 1;

SELECT T_DESC_ENGLISH,T_DESC_SPANISH,C_NAME, SUB_NAME, S_NAME FROM TIPS t
JOIN CATEGORY c ON 
t.C_ID = c.C_ID
JOIN SUBCATEGORY s ON 
t.SUB_ID = s.SUB_ID
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON sn ON
sn.S_ID = ts.S_ID 
WHERE t.C_ID = 1 AND t.SUB_ID = 5 AND sn.S_ID = 1;