SELECT T_DESC_ENGLISH, S_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID 
WHERE s.S_ID = 1

SELECT T_DESC_ENGLISH, S_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID 
WHERE s.S_ID = 2

SELECT T_DESC_ENGLISH, S_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID 
WHERE s.S_ID = 3

SELECT T_DESC_ENGLISH, S_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID 
WHERE s.S_ID = 4

SELECT T_DESC_ENGLISH, S_NAME FROM TIPS t
JOIN TIP_SEASON ts ON
t.T_ID = ts.T_ID
JOIN SEASON s ON
s.S_ID = ts.S_ID 
WHERE s.S_ID = 5