SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 1;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 2;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 3;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 4;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 5;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 6;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 7;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 8;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 9;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 10;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 11;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 12;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 13;

SELECT T_DESC_ENGLISH, T_DESC_SPANISH, SUB_NAME FROM TIPS t
JOIN SUBCATEGORY s 
ON t.SUB_ID = s.SUB_ID
WHERE t.SUB_ID = 14;