/*
SELECT * FROM TIP_FEEDBACK

UPDATE TIPS SET LIKES = LIKES + 1 WHERE T_ID = 1;

ALTER TABLE TIPS
ADD LIKES INT;

ALTER TABLE TIPS
ADD DISLIKES INT;

ALTER TABLE TIPS
ADD ADDPLANCLICKS INT;

UPDATE TIPS SET LIKES = 0;
UPDATE TIPS SET DISLIKES = 0;
UPDATE TIPS SET ADDPLANCLICKS = 0;

ALTER TABLE TIPS DROP COLUMN LIKES
ALTER TABLE TIPS DROP COLUMN DISLIKES
ALTER TABLE TIPS DROP COLUMN ADDPLANCLICKS

SELECT * FROM TIPS
*/

SELECT * FROM TIPS;

ALTER TABLE TIPS
ADD LIKES INT;

ALTER TABLE TIPS
ADD DISLIKES INT;

ALTER TABLE TIPS
ADD ADDPLANCLICKS INT;

UPDATE TIPS SET LIKES = 0;
UPDATE TIPS SET DISLIKES = 0;
UPDATE TIPS SET ADDPLANCLICKS = 0;